# -*- coding: utf-8 -*-
"""Semantic Similarity Analysis Using BERT-Based Models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MyZVmwsjHbSUEhLlhvrytEY8MQyLUK_c
"""

import pandas as pd
import numpy as np
import os
import glob
import kagglehub
import re
from sentence_transformers import SentenceTransformer
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline, MarianMTModel, MarianTokenizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler
from IPython.display import HTML, display
from datasets import load_dataset

class MoodMirrorCapstone:
    def __init__(self):
        print("⚙️ MoodMirror Capstone: Mühendislik Modülü Başlatılıyor...")

        # --- KONFİGÜRASYON VE HİPERPARAMETRELER ---
        self.CONF = {
            'sbert_model': 'sentence-transformers/all-mpnet-base-v2', # Yüksek doğruluklu model
            'trans_model': 'Helsinki-NLP/opus-mt-tr-en',             # Çeviri
            'sentiment_model': 'nlptown/bert-base-multilingual-uncased-sentiment', # Duygu Analizi
            'weights': {
                'similarity': 0.70,  # İçerik benzerliğinin ağırlığı
                'rating': 0.20,      # Kalite (Puan) ağırlığı
                'genre_match': 0.10  # Tür eşleşmesi bonusu
            },
            'top_k_retrieval': 100,  # İlk aşamada getirilecek aday sayısı
            'final_k': 4            # Kullanıcıya gösterilecek sayı
        }

        # MODELLERİN YÜKLENMESİ
        print("1. Çeviri Modülü (Encoder-Decoder) yükleniyor...")
        self.tr_tokenizer = MarianTokenizer.from_pretrained(self.CONF['trans_model'])
        self.tr_model = MarianMTModel.from_pretrained(self.CONF['trans_model'])

        print("2. Vektör Uzay Modeli (SBERT) yükleniyor...")
        self.sbert = SentenceTransformer(self.CONF['sbert_model'])

        print("3. Duygu Sınıflandırma Modeli (BERT) yükleniyor...")
        self.sent_pipe = pipeline("sentiment-analysis",
                                model=self.CONF['sentiment_model'],
                                tokenizer=self.CONF['sentiment_model'],
                                device=-1)

        # Veri Saklayıcılar
        self.journal_embeddings = None
        self.journal_df = None
        self.anime_embeddings = None
        self.anime_df = None

        # Tür Haritası (Genre Mapping)
        self.genre_map = {
            'Negative': ['Drama', 'Psychological', 'Thriller', 'Mystery', 'Supernatural', 'Horror'],
            'Positive': ['Comedy', 'Adventure', 'Action', 'Fantasy', 'Slice of Life', 'Sports'],
            'Mixed':    ['Slice of Life', 'Drama', 'Sci-Fi', 'Mystery', 'Seinen', 'Romance']
        }

    def preprocess_text(self, text):
        """Metin normalizasyonu (NLP Pipeline parçası)"""
        if not isinstance(text, str): return ""
        text = text.lower()
        text = re.sub(r'\s+', ' ', text) # Fazla boşlukları sil
        text = re.sub(r'[^\w\s]', '', text) # Noktalama işaretlerini kaldır
        return text.strip()

    def clean_anime_data(self, df):
        """
        Gelişmiş Veri Temizleme ve Tekilleştirme Fonksiyonu.
        """
        print("🧹 Veri Temizliği ve Tekilleştirme Başlıyor...")
        original_size = len(df)

        # 1. Regex ile Başlık Temizliği
        # Parantez içlerini (TV), (Special) vb. temizle
        df['clean_title'] = df['title'].str.replace(r"\(.*?\)", "", regex=True).str.strip()

        # 2. Yasaklı İçerik Filtresi (Noise Reduction)
        # Fragmanlar, Müzik Videoları, Reklamlar ve Özel Bölümler gürültü yaratır.
        banned_keywords = ['Yokoku', 'Trailer', 'CM', 'PV', 'Special', 'OVA', 'Music Video', 'Recap']
        pattern = '|'.join(banned_keywords)
        df = df[~df['title'].str.contains(pattern, case=False, regex=True)]

        # 3. Anlamsal Tekilleştirme (Deduplication)
        # Aynı isme sahip serilerden sadece en yüksek puanlı olanı tut.
        # Örn: "Naruto" ve "Naruto (2002)" varsa puanı yüksek olan kalır.
        df = df.sort_values('score', ascending=False)
        df = df.drop_duplicates(subset=['clean_title'], keep='first')

        # 4. Eksik Veri Temizliği
        df = df[df['synopsis'].str.len() > 50] # 50 karakterden kısa özetleri at

        print(f"✅ Temizlik Tamamlandı: {original_size} -> {len(df)} kayıt kaldı.")
        return df.reset_index(drop=True)

    def feature_engineering(self):
        """
        Vektör başarısını artırmak için özellik mühendisliği.
        Sadece özeti değil, türü ve başlığı da vektöre dahil eder.
        """
        # Puanları 0-1 arasına normalize et (Hibrit skorlama için gerekli)
        scaler = MinMaxScaler()
        self.anime_df['normalized_score'] = scaler.fit_transform(self.anime_df[['score']])

        # Zenginleştirilmiş Metin (Enriched Context)
        self.anime_df['embedding_text'] = self.anime_df.apply(
            lambda x: f"Title: {x['clean_title']}. Genre: {x['genre']}. Plot: {x['synopsis']}",
            axis=1
        )

    def load_datasets(self):
        # --- 1. GÜNLÜK VERİSİ (HuggingFace) ---
        print(f"📂 Verisetleri Yükleniyor...")
        try:
            ds = load_dataset("dair-ai/emotion")
            self.journal_df = pd.DataFrame(ds['train'])
            # Etiketleme (0:sadness, 1:joy, 2:love, 3:anger, 4:fear, 5:surprise)
            self.journal_df['Sentiment_Label'] = self.journal_df['label'].map(
                {0:'Negative', 1:'Positive', 2:'Positive', 3:'Negative', 4:'Negative', 5:'Positive'}
            )
            # Vektörleştirme
            self.journal_embeddings = self.sbert.encode(self.journal_df['text'].tolist(), show_progress_bar=False)
        except Exception as e:
            print(f"⚠️ Günlük verisi uyarısı: {e}")

        # --- 2. ANIME VERİSİ (KaggleHub) ---
        try:
            path = kagglehub.dataset_download("marlesson/myanimelist-dataset-animes-profiles-reviews")
            csv_file = glob.glob(os.path.join(path, "animes.csv"))[0]

            df = pd.read_csv(csv_file)
            # Gerekli sütunlar
            df = df[['uid', 'title', 'synopsis', 'genre', 'img_url', 'score']].dropna()

            # Filtreler
            df = df[df['score'] > 6.0] # Kalite filtresi
            banned_genres = ['Hentai', 'Ecchi', 'Erotica', 'Yaoi', 'Yuri']
            df = df[~df['genre'].str.contains('|'.join(banned_genres), case=False)]

            # TEMİZLİK FONKSİYONU
            self.anime_df = self.clean_anime_data(df)

            # ÖZELLİK MÜHENDİSLİĞİ
            self.feature_engineering()

            # VEKTÖRLEŞTİRME
            print("🧠 Anime veritabanı vektör uzayına aktarılıyor (Bu işlem 1-2 dk sürebilir)...")
            # Performans için ilk 7000 kayıt
            self.anime_df = self.anime_df.iloc[:7000]
            self.anime_embeddings = self.sbert.encode(self.anime_df['embedding_text'].tolist(), show_progress_bar=True)
            print("✅ Sistem Hazır.")

        except Exception as e:
            print(f"❌ Kritik Hata: {e}")

    def translate(self, text):
        """Türkçe -> İngilizce Çeviri"""
        try:
            inputs = self.tr_tokenizer(text, return_tensors="pt", padding=True)
            translated = self.tr_model.generate(**inputs)
            return self.tr_tokenizer.batch_decode(translated, skip_special_tokens=True)[0]
        except: return text

    def calculate_hybrid_score(self, cosine_sim, normalized_rating, genre_match):
        """
        Hibrit Skorlama Formülü (Bitirme Projesi Metodolojisi)
        Score = (w1 * Sim) + (w2 * Rating) + (w3 * Genre)
        """
        w = self.CONF['weights']
        final_score = (w['similarity'] * cosine_sim) + \
                      (w['rating'] * normalized_rating) + \
                      (w['genre_match'] * genre_match)
        return final_score

    def generate_explanation_mock(self, user_mood, anime_title, anime_plot):
        """
        RAG (Retrieval-Augmented Generation) Simülasyonu.
        """
        templates = [
            f"Since you're feeling {user_mood}, '{anime_title}' offers a perfect escape. {anime_plot[:100]}...",
            f"Based on your mood ({user_mood}), I recommend '{anime_title}'. It deals with similar themes effectively.",
            f"To help with your {user_mood} state, try '{anime_title}'. Its story might resonate with you."
        ]
        return np.random.choice(templates)

    def recommend(self, user_query_tr):
        print(f"\n🔍 Analiz Ediliyor: '{user_query_tr}'")

        # 1. Çeviri
        query_en = self.translate(user_query_tr)
        print(f"🇬🇧 Sistem Algısı (EN): {query_en}")

        # 2. Duygu Analizi
        sentiment_res = self.sent_pipe(user_query_tr[:512])[0]
        stars = int(sentiment_res['label'].split()[0])
        mood = 'Negative' if stars <= 2 else 'Positive' if stars >= 4 else 'Mixed'
        target_genres = self.genre_map[mood]
        print(f"📊 Algılanan Duygu Modu: {mood.upper()} ({stars}/5 Yıldız)")

        # 3. Vektör Arama (Retrieval)
        query_vec = self.sbert.encode([query_en])
        sims = cosine_similarity(query_vec, self.anime_embeddings)[0]

        # 4. Hibrit Skorlama ve Sıralama (Ranking)
        scored_results = []

        for idx in range(len(self.anime_df)):
            row = self.anime_df.iloc[idx]

            # Parametreler
            sim_score = sims[idx]
            rating_score = row['normalized_score']

            # Tür Eşleşmesi (Binary veya Soft Match)
            row_genres = str(row['genre'])
            genre_bonus = 1.0 if any(g in row_genres for g in target_genres) else 0.0

            # FORMÜL UYGULAMA
            final_score = self.calculate_hybrid_score(sim_score, rating_score, genre_bonus)

            scored_results.append((idx, final_score, sim_score))

        # Puana göre sırala
        scored_results.sort(key=lambda x: x[1], reverse=True)

        # 5. Çeşitlilik Filtresi (Diversity Filter)
        final_recommendations = []
        seen_titles = set()

        for idx, f_score, sim_score in scored_results:
            if len(final_recommendations) >= self.CONF['final_k']: break

            row = self.anime_df.iloc[idx]

            # İsim Kökü Kontrolü (Tekrarı önlemek için)
            title_root = row['clean_title'].split()[0].lower()
            if len(title_root) > 3 and title_root in seen_titles: continue

            # RAG Açıklaması Üret (Simüle)
            explanation = self.generate_explanation_mock(mood, row['clean_title'], row['synopsis'])

            final_recommendations.append({
                'data': row,
                'match_score': int(f_score * 100),
                'sim_score': int(sim_score * 100),
                'explanation': explanation
            })
            seen_titles.add(title_root)

        return final_recommendations, mood, query_en

    def render_ui(self, results, user_input, mood):
        """Sonuçları Profesyonel HTML Kartları olarak basar"""
        if not results: return print("Sonuç bulunamadı.")

        anchor = results[0]
        others = results[1:]

        html = f"""
        <style>
            .mm-box {{ font-family: 'Segoe UI', sans-serif; background: #121212; color: #e0e0e0; padding: 25px; border-radius: 15px; max-width: 800px; margin: 0 auto; box-shadow: 0 10px 30px rgba(0,0,0,0.6); }}
            .mm-hero {{ display: flex; gap: 20px; background: #1f1f1f; padding: 20px; border-radius: 12px; border: 1px solid #333; }}
            .mm-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin-top: 20px; }}
            .mm-card {{ background: #1f1f1f; padding: 15px; border-radius: 10px; text-align: center; border: 1px solid #333; }}
            .badge {{ padding: 3px 8px; border-radius: 4px; font-size: 11px; font-weight: bold; }}
            .b-blue {{ background: #3b82f6; color: white; }}
            .b-purp {{ background: #8b5cf6; color: white; }}
        </style>

        <div class="mm-box">
            <div style="text-align:center; margin-bottom:20px; border-bottom:1px solid #333; padding-bottom:10px;">
                <h2 style="margin:0; background: linear-gradient(90deg, #3b82f6, #8b5cf6); -webkit-background-clip: text; -webkit-text-fill-color: transparent;">MOOD MIRROR CAPSTONE</h2>
                <div style="font-size:12px; color:#888;">INPUT: "{user_input}" • MOOD: {mood}</div>
            </div>

            <div class="mm-hero">
                <img src="{anchor['data']['img_url']}" style="width:140px; height:210px; object-fit:cover; border-radius:8px;">
                <div>
                    <h3 style="margin:0 0 5px 0; color:white;">{anchor['data']['clean_title']}</h3>
                    <div style="margin-bottom:10px;">
                        <span class="badge b-blue">%{anchor['match_score']} MATCH</span>
                        <span class="badge b-purp">IMDB: {anchor['data']['score']}</span>
                    </div>
                    <div style="font-style:italic; color:#aaa; font-size:13px; margin-bottom:10px; border-left:3px solid #3b82f6; padding-left:10px;">
                        AI Insight: {anchor['explanation']}
                    </div>
                    <p style="font-size:13px; color:#ccc; line-height:1.4;">{anchor['data']['synopsis'][:250]}...</p>
                </div>
            </div>

            <div class="mm-grid">
        """

        for item in others:
            html += f"""
                <div class="mm-card">
                    <img src="{item['data']['img_url']}" style="width:100%; height:130px; object-fit:cover; border-radius:6px; margin-bottom:8px;">
                    <div style="font-size:12px; font-weight:bold; white-space:nowrap; overflow:hidden; text-overflow:ellipsis;">{item['data']['clean_title']}</div>
                    <div style="margin-top:5px;">
                        <span class="badge b-blue">%{item['match_score']}</span>
                    </div>
                </div>
            """

        html += "</div></div>"
        display(HTML(html))

# --- ÇALIŞTIRMA KODU ---
if __name__ == "__main__":
    # Sınıfı Başlat
    app = MoodMirrorCapstone()

    # Verileri Yükle
    app.load_datasets()

    # Kullanıcıdan Girdi Al
    user_input = input("🗨️ (MoodMirror) Lütfen hislerini veya aradığın hikayeyi anlat: ")

    # Öneri Motorunu Çalıştır
    recs, mood, query_en = app.recommend(user_input)

    # Sonucu Göster
    app.render_ui(recs, user_input, mood)